In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
%matplotlib inline

In [2]:
df = pd.read_csv("Loan Eligibility Prediction.csv")
df

Customer_ID  Gender Married  Dependents     Education Self_Employed  \
0            569  Female      No           0      Graduate            No   
1             15    Male     Yes           2      Graduate            No   
2             95    Male      No           0  Not Graduate            No   
3            134    Male     Yes           0      Graduate           Yes   
4            556    Male     Yes           1      Graduate            No   
..           ...     ...     ...         ...           ...           ...   
609          480    Male     Yes           2      Graduate            No   
610          525    Male      No           0      Graduate            No   
611          551    Male     Yes           2      Graduate           Yes   
612          552    Male     Yes           1  Not Graduate            No   
613          606    Male     Yes           0  Not Graduate            No   

     Applicant_Income  Coapplicant_Income  Loan_Amount  Loan_Amount_Term  \
0                2378                 0.0            9               360   
1                1299              1086.0           17               120   
2                3620                 0.0           25               120   
3                3459                 0.0           25               120   
4                5468              1032.0           26               360   
..                ...                 ...          ...               ...   
609              2947              1603.0           10               360   
610              4680              2087.0           15               360   
611              6633                 0.0           25               360   
612              2492              2375.0           30               360   
613              2400              3800.0           25               180   

     Credit_History Property_Area Loan_Status  
0                 1         Urban           N  
1                 1         Urban           Y  
2                 1     Semiurban           Y  
3                 1     Semiurban           Y  
4                 1     Semiurban           Y  
..              ...           ...         ...  
609               1         Urban           N  
610               1     Semiurban           N  
611               0         Rural           N  
612               1         Rural           Y  
613               1         Urban           N  

[614 rows x 13 columns]

In [3]:
# converting categorical to numerical
df['Gender'] = df['Gender'].map({"Male":0,"Female" :1})
df['Gender']


0      1
1      0
2      0
3      0
4      0
      ..
609    0
610    0
611    0
612    0
613    0
Name: Gender, Length: 614, dtype: int64

In [4]:
df['Married'] = df['Married'].map({"No":0,"Yes" :1})
df['Married']

0      0
1      1
2      0
3      1
4      1
      ..
609    1
610    0
611    1
612    1
613    1
Name: Married, Length: 614, dtype: int64

In [5]:
df['Education'] = df['Education'].map({"Not Graduate":0,"Graduate" :1})
df['Education']

0      1
1      1
2      0
3      1
4      1
      ..
609    1
610    1
611    1
612    0
613    0
Name: Education, Length: 614, dtype: int64

In [6]:
df['Self_Employed'] = df['Self_Employed'].map({"No":0,"Yes" :1})
df['Self_Employed'] 

0      0
1      0
2      0
3      1
4      0
      ..
609    0
610    0
611    1
612    0
613    0
Name: Self_Employed, Length: 614, dtype: int64

In [7]:
df['Loan_Status'] = df['Loan_Status'].map({"N":0, "Y" :1})
df['Loan_Status'] 

0      0
1      1
2      1
3      1
4      1
      ..
609    0
610    0
611    0
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int64

In [8]:
df

Customer_ID  Gender  Married  Dependents  Education  Self_Employed  \
0            569       1        0           0          1              0   
1             15       0        1           2          1              0   
2             95       0        0           0          0              0   
3            134       0        1           0          1              1   
4            556       0        1           1          1              0   
..           ...     ...      ...         ...        ...            ...   
609          480       0        1           2          1              0   
610          525       0        0           0          1              0   
611          551       0        1           2          1              1   
612          552       0        1           1          0              0   
613          606       0        1           0          0              0   

     Applicant_Income  Coapplicant_Income  Loan_Amount  Loan_Amount_Term  \
0                2378                 0.0            9               360   
1                1299              1086.0           17               120   
2                3620                 0.0           25               120   
3                3459                 0.0           25               120   
4                5468              1032.0           26               360   
..                ...                 ...          ...               ...   
609              2947              1603.0           10               360   
610              4680              2087.0           15               360   
611              6633                 0.0           25               360   
612              2492              2375.0           30               360   
613              2400              3800.0           25               180   

     Credit_History Property_Area  Loan_Status  
0                 1         Urban            0  
1                 1         Urban            1  
2                 1     Semiurban            1  
3                 1     Semiurban            1  
4                 1     Semiurban            1  
..              ...           ...          ...  
609               1         Urban            0  
610               1     Semiurban            0  
611               0         Rural            0  
612               1         Rural            1  
613               1         Urban            0  

[614 rows x 13 columns]

In [9]:
new_df = df.drop(['Customer_ID', 'Dependents', 'Coapplicant_Income', 'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'], axis=1)
new_df

Gender  Married  Education  Self_Employed  Applicant_Income  Loan_Amount
0         1        0          1              0              2378            9
1         0        1          1              0              1299           17
2         0        0          0              0              3620           25
3         0        1          1              1              3459           25
4         0        1          1              0              5468           26
..      ...      ...        ...            ...               ...          ...
609       0        1          1              0              2947           10
610       0        0          1              0              4680           15
611       0        1          1              1              6633           25
612       0        1          0              0              2492           30
613       0        1          0              0              2400           25

[614 rows x 6 columns]

In [10]:
Loan_Status = df.Loan_Status
Loan_Status

0      0
1      1
2      1
3      1
4      1
      ..
609    0
610    0
611    0
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split


In [12]:
x_train,x_test,y_train,y_test = train_test_split(new_df,Loan_Status,train_size = 0.8)


In [13]:
x_train

Gender  Married  Education  Self_Employed  Applicant_Income  Loan_Amount
401       0        1          1              0              3015          153
343       1        0          1              0              3762          135
44        0        1          0              0              2917           66
282       0        1          0              1              7100          125
175       0        0          1              0              3617          107
..      ...      ...        ...            ...               ...          ...
11        0        1          1              0              3716           42
32        0        0          1              0              2479           59
603       0        0          0              0              2000           30
285       0        1          1              0              5488          125
539       0        1          1              0              6065          250

[491 rows x 6 columns]

In [14]:
y_train

401    1
343    1
44     0
282    1
175    1
      ..
11     1
32     1
603    0
285    1
539    1
Name: Loan_Status, Length: 491, dtype: int64

In [15]:
x_test

Gender  Married  Education  Self_Employed  Applicant_Income  Loan_Amount
461       0        1          1              0              7333          175
367       0        0          1              0              6000          140
194       0        1          1              0              4333          110
328       0        0          0              1              5800          132
345       1        0          1              0              4300          136
..      ...      ...        ...            ...               ...          ...
426       0        1          1              0              2499          160
531       0        1          1              0             10833          234
83        1        0          0              0              4606           81
576       0        1          1              1              9323          380
605       1        0          0              0              1830           35

[123 rows x 6 columns]

In [16]:
model = linear_model.LogisticRegression()
model.fit(x_train,y_train)
model

LogisticRegression()

In [31]:
y_test

358    1
5      1
578    1
571    0
384    0
      ..
67     1
138    0
560    1
47     0
58     0
Name: Loan_Status, Length: 123, dtype: int64

In [17]:
y_pred = model.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [18]:
model.score(x_test,y_test)

0.6829268292682927

In [19]:
model.coef_

array([[ 8.43849267e-06,  4.51656845e-05,  4.63715723e-05,
         4.74815153e-06, -2.14387141e-06,  4.14050979e-03]])

In [20]:
model.intercept_

array([4.8269572e-05])